---
- name: Deploy Nginx and HTML template
  hosts: all
  become: true
  
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: present
  
  - name: Open firewall on port 80
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
  
  - name: Deploy HTML template
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
      mode: '0644'
  
  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: true